# Generated by Django 2.1.2 on 2018-12-05 11:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=100, unique=True)),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=100, unique=True)),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=100, unique=True)),
                ('reference', models.CharField(default='', max_length=100)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contenantCoffret', models.IntegerField(default='1', null=True)),
                ('testContenant', models.IntegerField(default='1', null=True)),
                ('cmm', models.IntegerField(default='1', null=True)),
                ('StockMiniMois', models.IntegerField(default='1', null=True)),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='productAPI.Famille')),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='productAPI.Laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_lot', models.CharField(default='', max_length=100)),
                ('quantite', models.IntegerField(default='1')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('peremption_date', models.DateField(default=datetime.date.today)),
                ('trans_type', models.CharField(choices=[('IN', 'ENTREE'), ('OUT', 'SORTIE')], max_length=10)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='productAPI.Product')),
            ],
        ),
    ]
