# Generated by Django 2.1.2 on 2018-12-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttrans',
            old_name='produit',
            new_name='product',
        ),
    ]
