# Generated by Django 2.1.2 on 2018-12-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='StockMiniMois',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cmm',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contenantCoffret',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='testContenant',
            field=models.IntegerField(default='1'),
        ),
    ]
