# Generated by Django 2.1.2 on 2018-10-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Laboratoire_2',
        ),
        migrations.AlterField(
            model_name='famille',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
