# Generated by Django 2.0.2 on 2018-09-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='refrence',
            new_name='reference',
        ),
    ]
