# Generated by Django 2.1.2 on 2018-12-04 17:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='laboratoire',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producttrans',
            name='modification_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
