# Generated by Django 2.1.2 on 2018-11-23 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0002_auto_20181111_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.IntegerField(unique=True)),
                ('quantite', models.IntegerField(default='1')),
                ('modification_date', models.DateTimeField(default=datetime.date.today)),
                ('peremption_date', models.DateField(default=datetime.date.today)),
                ('trans_type', models.CharField(choices=[('IN', 'ENTREE'), ('OUT', 'SORTIE')], max_length=10)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='productAPI.Product')),
            ],
        ),
    ]
