# Generated by Django 2.1.2 on 2018-11-09 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0003_auto_20181005_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='familles',
            new_name='famille',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='laboratoires',
            new_name='laboratoire',
        ),
    ]
