# Generated by Django 2.0.2 on 2018-09-29 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0003_auto_20180928_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='CMM',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='StockMiniMois',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='contenantCoffret',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='testContenant',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productAPI.Famille'),
        ),
        migrations.AddField(
            model_name='product',
            name='laboratoire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productAPI.Laboratoire'),
        ),
    ]
