# Generated by Django 2.0.2 on 2018-09-29 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0004_auto_20180929_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='CMM',
            new_name='cmm',
        ),
    ]
