# Generated by Django 2.1.2 on 2018-12-04 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0004_auto_20181123_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='famille',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='famille',
            name='modification_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='laboratoire',
            name='modification_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='modification_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='producttrans',
            name='creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
