# Generated by Django 2.0.2 on 2018-09-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0006_auto_20180929_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='StockMiniMois',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cmm',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='contenantCoffret',
            field=models.IntegerField(default='1', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='testContenant',
            field=models.IntegerField(default='1', null=True),
        ),
    ]
