# Generated by Django 2.0.2 on 2018-09-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAPI', '0007_auto_20180929_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='famille',
            new_name='familles',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='laboratoire',
            new_name='laboratoires',
        ),
    ]
